apiVersion: v2
name: nginx-helm
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: nginx
    repository: https://charts.bitnami.com/bitnami
    version: 13.2.3